<?php //print_r(get_defined_vars());die;?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">

<body>
<h1>Здравствуйте, <?php echo $declarant["name"];?>!</h1>
Ваши заявки на модерацию в конкурсе детского рисунка телерадиокомпании «Мир», посвященному Дню космонавтики приняты.<br><br> 
Заявкам присвоены следующие номера:<br> 
<?php foreach($participants as $currentOne):?>
<?php echo $currentOne["name"];?> <?php echo $currentOne["surname"];?>, заявка номер <?php echo $queueNum[$currentOne["idParticipant"]];?><br>
<?php endforeach;?><br>
После модерации Вам будет выслано уведомление, с информацией о том: пройдена ли модерация и в случае удачного прохождения модерации - присвоены номера участников Акции. (Номер участника Акции не может быть больше номера Заявки на модерацию).<br>
С правилами проведения конкурса Вы можете ознакомиться на <a href="http://konkurs.mir24.tv/rules.pdf">сайте</a><br> 
Пишите нам: <a href="mailto:risunok@mirtv.ru">risunok@mirtv.ru</a><br>
</body>

</html>
