<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Мир без войны</title>
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1"
    >
    <meta property="og:title" content="Мир без войны"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="http://<?=$_SERVER["SERVER_NAME"]?>/photo/<?= $result['idContribution'] ?>"/>
    <meta property="og:image" content="http://<?=$_SERVER["SERVER_NAME"]?><?= $result['webPath'] ?>"/>
    <meta property="og:site_name" content="Мир без войны"/>
    <meta property="og:description" content="<?= $result['description'] ?>"/>
</head>
<body>
<p>Мир без войны: Детальная</p>
</body>
</html>
