<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Конкурс рисунка</title>
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1"
    >
    <link rel="stylesheet" type="text/css" href="/main.css">
    <link rel='stylesheet' type="text/css" href='/detail.css'>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
</head>
<body>
<header class="header">
    <div id="logo" style="float:left;">
        <a href="http://mir24.tv">
            <img src="http://mir24.tv/media/images/mir2/mir_logo_80.png" alt="24 МИР" title="24 МИР">
        </a>
    </div>
    <div style="margin: auto;">
        <h1 style="margin: 47px;float: left;">
            Конкурс рисунка
        </h1>
    </div>
</header>
<div class="content">
    <a title="Посмотреть в полном размере" href="http://konkurs.mir24.tv<?= $targetWork['webPath'] ?>" target="_blank">
        <img class="image_detail" src="http://konkurs.mir24.tv<?= $targetWork['webPath'] ?>">
    </a>
    <div class="info-wrap">
        <div class="image_info">
            <p>Конкурсант: <?= $targetWork['participant_name'] . ' ' . $targetWork['participant_surname'] ?><br/>
                Возраст: <?= $targetWork['age'] ?> <?= $targetWork['age_string'] ?></p>
            <? if (1) { ?>
                <form name="fdfs" method="POST" action="/api/v1/vote">
                    <input type="hidden" name="id_competitive_work" value="<?= $targetWork['idCompetitiveWork'] ?>"/>
                    <input type="submit" class="vote" value="Проголосовать">
                </form>
            <? } else { ?>
                <div class="no-vote">Вы уже голосовали сегодня</div>
            <? } ?>
        </div>
    </div>
</div>
</body>

</html>
