<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Конкурс рисунка</title>
  <meta name="description" content="Google's material design UI components built with React.">

  <!-- Use minimum-scale=1 to enable GPU rasterization -->
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, user-scalable=0, maximum-scale=1, minimum-scale=1"
  >
  <link rel="stylesheet" type="text/css" href="/main.css?2202">
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
</head>

<body>
  <div class="wrapper">
    <header class="header">
      <div id="logo" style="float:left;">
        <a href="http://mir24.tv">
          <img src="http://mir24.tv/media/images/mir2/mir_logo_80.png" alt="24 МИР" title="24 МИР">
        </a>
      </div>
      <div style="float:right; margin:1%;">
        <a href="/rules.pdf" target="_blank">
            Правила конкурса
        </a>
      </div>
    </header>
    <main class="content">
      <div id="app"></div>
    </main>
  </div><!-- .wrapper -->
  <footer class="footer">
  </footer>
  <!-- This script adds the Roboto font to our project. For more detail go to this site:  http://www.google.com/fonts#UsePlace:use/Collection:Roboto:400,300,500 -->
  <script>
    var WebFontConfig = {
      google: { families: [ 'Roboto:400,300,500:latin' ] }
    };
    (function() {
      var wf = document.createElement('script');
      wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
      wf.type = 'text/javascript';
      wf.async = 'true';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(wf, s);
    })();
  </script>
  <script src="app.js?2202"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-75143191-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>

</html>
